name: mine
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2021.7.5=h06a4308_1
  - certifi=2021.5.30=py37h06a4308_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1k=h27cfd23_0
  - pip=21.2.2=py37h06a4308_0
  - python=3.7.11=h12debd9_0
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py37h06a4308_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - cachetools==4.2.2
    - charset-normalizer==2.0.4
    - click==8.0.1
    - cloudpickle==1.6.0
    - colabgymrender==1.0.9
    - configparser==5.0.2
    - daal==2021.3.0
    - daal4py==2021.3.0
    - decorator==4.4.2
    - dm-tree==0.1.6
    - docker-pycreds==0.4.0
    - easyprocess==0.3
    - evdev==1.4.0
    - filelock==3.0.12
    - gitdb==4.0.7
    - gitpython==3.1.18
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.5
    - grpcio==1.39.0
    - gym==0.18.3
    - hummingbird-ml==0.4.1
    - idna==3.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.5
    - imutils==0.5.4
    - joblib==1.0.1
    - keyboard==0.13.5
    - lightgbm==3.2.1
    - lz4==3.1.3
    - markdown==3.3.4
    - markupsafe==2.0.1
    - minerl==0.4.0
    - moviepy==1.0.3
    - msgpack==1.0.2
    - numpy==1.21.1
    - oauthlib==3.1.1
    - onnx==1.10.1
    - onnxconverter-common==1.8.1
    - opencv-contrib-python==4.0.0.21
    - opencv-python==4.0.0.21
    - pairing==0.1.3
    - pandas==1.3.2
    - pathtools==0.1.2
    - pfrl==0.3.0
    - pillow==8.2.0
    - proglog==0.1.9
    - promise==2.3
    - protobuf==3.17.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyglet==1.5.15
    - pynput==1.7.3
    - pyparsing==2.4.7
    - python-xlib==0.31
    - pytz==2021.1
    - pyvirtualdisplay==2.2
    - pyyaml==5.4.1
    - ray==1.6.0
    - redis==3.5.3
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scikit-learn==0.24.2
    - scipy==1.7.1
    - seaborn==0.11.2
    - sentry-sdk==1.3.1
    - shortuuid==1.0.1
    - six==1.16.0
    - sklearn==0.0
    - smmap==4.0.0
    - stable-baselines3==1.1.0
    - subprocess32==3.5.4
    - tabulate==0.8.9
    - tbb==2021.3.0
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.4
    - threadpoolctl==2.2.0
    - torch==1.9.0
    - torchaudio==0.9.0
    - torchvision==0.10.0
    - tqdm==4.62.0
    - urllib3==1.26.6
    - wandb==0.12.0
    - werkzeug==2.0.1
prefix: /home/dang/anaconda3/envs/mine
